[project]
name = "nano-llm-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "mirascope>=1.18.4",
    "nanodjango>=0.10.0",
    "openai>=1.63.2",
]
